import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import usersRouter from "./users";
import materialCatalogRouter from "./materialCatalog";
import jobsRouter from "./jobs";
import estimatesRouter from "./estimates";
import stagesRouter from "./stages";
import stageLibraryRouter from "./stageLibrary";
import employeesRouter from "./employees";
import timeRouter from "./time";
import dashboardRouter from "./dashboard";
import documentsRouter from "./documents";
import customersRouter from "./customers";
import bomRouter from "./bom";
import purchaseOrdersRouter from "./purchaseOrders";
import jobHandoffsRouter from "./jobHandoffs";
import drawingsRouter from "./drawings";
import rfisRouter from "./rfis";
import ecnsRouter from "./ecns";
import transmittalsRouter from "./transmittals";
import vendorsRouter from "./vendors";
import qualityClausesRouter from "./qualityClauses";
import poApprovalThresholdsRouter from "./poApprovalThresholds";
import estimateBomRouter from "./estimateBom";
import laborRatesRouter from "./laborRates";
import quoteRouter from "./quote";
import inventoryRouter from "./inventory";
import nestingRouter from "./nesting";
import qcRouter from "./qc";
import shippingRouter from "./shipping";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(usersRouter);
router.use(materialCatalogRouter);
router.use(jobsRouter);
router.use(estimatesRouter);
router.use(stagesRouter);
router.use(stageLibraryRouter);
router.use(employeesRouter);
router.use(timeRouter);
router.use(dashboardRouter);
router.use(documentsRouter);
router.use(customersRouter);
router.use(bomRouter);
router.use(vendorsRouter);
router.use(qualityClausesRouter);
router.use(poApprovalThresholdsRouter);
router.use(purchaseOrdersRouter);
router.use(inventoryRouter);
router.use(jobHandoffsRouter);
router.use(drawingsRouter);
router.use(rfisRouter);
router.use(ecnsRouter);
router.use(transmittalsRouter);
router.use(estimateBomRouter);
router.use(laborRatesRouter);

router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(usersRouter);
router.use(materialCatalogRouter);
router.use(jobsRouter);
router.use(estimatesRouter);
router.use(stagesRouter);
router.use(stageLibraryRouter);
router.use(employeesRouter);
router.use(timeRouter);
router.use(dashboardRouter);
router.use(documentsRouter);
router.use(customersRouter);
router.use(bomRouter);
router.use(vendorsRouter);
router.use(qualityClausesRouter);
router.use(poApprovalThresholdsRouter);
router.use(purchaseOrdersRouter);
router.use(inventoryRouter);
router.use(jobHandoffsRouter);
router.use(drawingsRouter);
router.use(rfisRouter);
router.use(ecnsRouter);
router.use(transmittalsRouter);
router.use(estimateBomRouter);
router.use(laborRatesRouter);
router.use(quoteRouter);
router.use(nestingRouter);
router.use(qcRouter);
router.use(shippingRouter);

export default router;
